# Generated by Django 4.2.2 on 2023-06-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_consumer_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionFactsLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saturated_fats', models.DecimalField(decimal_places=2, max_digits=6)),
                ('polyunsaturated_fats', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monounsaturated_fats', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dietary_fiber', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sugars', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('data_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='groceries.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seller')),
                ('diet', models.ManyToManyField(to='groceries.diet')),
                ('nutrition_facts_label', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groceries.nutritionfactslabel')),
            ],
            options={
                'verbose_name_plural': 'groceries',
            },
        ),
    ]
