# Generated by Django 4.2.2 on 2023-06-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='grocery',
            old_name='diet',
            new_name='diets',
        ),
    ]
