# Generated by Django 4.2.2 on 2023-07-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_rename_category_grocery_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='data_modified',
            new_name='date_modified',
        ),
    ]
