# Generated by Django 4.2.2 on 2023-07-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name_plural': 'Payment details'},
        ),
    ]
